/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdvOptions.java
 *
 * Created on Nov 24, 2008, 2:18:06 PM
 */

package imi.gui;

/**
 *
 * @author ptruong
 */
public class AdvOptions extends javax.swing.JFrame {

    /** Creates new form AdvOptions */
    public AdvOptions() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane_Main = new javax.swing.JTabbedPane();
        jPanel_MainHead = new javax.swing.JPanel();
        jTabbedPane_Head = new javax.swing.JTabbedPane();
        jPanel_Eyes = new javax.swing.JPanel();
        jPanel_Nose = new javax.swing.JPanel();
        jPanel_Mouth = new javax.swing.JPanel();
        jPanel_UniformHead = new javax.swing.JPanel();
        jPanel_MainArmsHands = new javax.swing.JPanel();
        jTabbedPane_ArmsHands = new javax.swing.JTabbedPane();
        jPanel_Hands = new javax.swing.JPanel();
        jPanel_Forearms = new javax.swing.JPanel();
        jPanel_UpperArms = new javax.swing.JPanel();
        jPanel_LegsFeet = new javax.swing.JPanel();
        jTabbedPane_LegsFeet = new javax.swing.JTabbedPane();
        jPanel_Feet = new javax.swing.JPanel();
        jPanel_Calves = new javax.swing.JPanel();
        jPanel_Thighs = new javax.swing.JPanel();
        jPanel_Body = new javax.swing.JPanel();
        jTabbedPane_Body = new javax.swing.JTabbedPane();
        jPanel_Chest = new javax.swing.JPanel();
        jPanel_Abs = new javax.swing.JPanel();
        jPanel_Gluts = new javax.swing.JPanel();
        jPanel_UniformBody = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane_Head.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        org.jdesktop.layout.GroupLayout jPanel_EyesLayout = new org.jdesktop.layout.GroupLayout(jPanel_Eyes);
        jPanel_Eyes.setLayout(jPanel_EyesLayout);
        jPanel_EyesLayout.setHorizontalGroup(
            jPanel_EyesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 333, Short.MAX_VALUE)
        );
        jPanel_EyesLayout.setVerticalGroup(
            jPanel_EyesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 388, Short.MAX_VALUE)
        );

        jTabbedPane_Head.addTab("Eyes", jPanel_Eyes);

        org.jdesktop.layout.GroupLayout jPanel_NoseLayout = new org.jdesktop.layout.GroupLayout(jPanel_Nose);
        jPanel_Nose.setLayout(jPanel_NoseLayout);
        jPanel_NoseLayout.setHorizontalGroup(
            jPanel_NoseLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 333, Short.MAX_VALUE)
        );
        jPanel_NoseLayout.setVerticalGroup(
            jPanel_NoseLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 388, Short.MAX_VALUE)
        );

        jTabbedPane_Head.addTab("Nose", jPanel_Nose);

        org.jdesktop.layout.GroupLayout jPanel_MouthLayout = new org.jdesktop.layout.GroupLayout(jPanel_Mouth);
        jPanel_Mouth.setLayout(jPanel_MouthLayout);
        jPanel_MouthLayout.setHorizontalGroup(
            jPanel_MouthLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 333, Short.MAX_VALUE)
        );
        jPanel_MouthLayout.setVerticalGroup(
            jPanel_MouthLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 388, Short.MAX_VALUE)
        );

        jTabbedPane_Head.addTab("Mouth", jPanel_Mouth);

        org.jdesktop.layout.GroupLayout jPanel_UniformHeadLayout = new org.jdesktop.layout.GroupLayout(jPanel_UniformHead);
        jPanel_UniformHead.setLayout(jPanel_UniformHeadLayout);
        jPanel_UniformHeadLayout.setHorizontalGroup(
            jPanel_UniformHeadLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 333, Short.MAX_VALUE)
        );
        jPanel_UniformHeadLayout.setVerticalGroup(
            jPanel_UniformHeadLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 388, Short.MAX_VALUE)
        );

        jTabbedPane_Head.addTab("Uniform", jPanel_UniformHead);

        org.jdesktop.layout.GroupLayout jPanel_MainHeadLayout = new org.jdesktop.layout.GroupLayout(jPanel_MainHead);
        jPanel_MainHead.setLayout(jPanel_MainHeadLayout);
        jPanel_MainHeadLayout.setHorizontalGroup(
            jPanel_MainHeadLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPane_Head, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );
        jPanel_MainHeadLayout.setVerticalGroup(
            jPanel_MainHeadLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPane_Head, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
        );

        jTabbedPane_Main.addTab("Head", jPanel_MainHead);

        jTabbedPane_ArmsHands.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        org.jdesktop.layout.GroupLayout jPanel_HandsLayout = new org.jdesktop.layout.GroupLayout(jPanel_Hands);
        jPanel_Hands.setLayout(jPanel_HandsLayout);
        jPanel_HandsLayout.setHorizontalGroup(
            jPanel_HandsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 333, Short.MAX_VALUE)
        );
        jPanel_HandsLayout.setVerticalGroup(
            jPanel_HandsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 388, Short.MAX_VALUE)
        );

        jTabbedPane_ArmsHands.addTab("Hands", jPanel_Hands);

        org.jdesktop.layout.GroupLayout jPanel_ForearmsLayout = new org.jdesktop.layout.GroupLayout(jPanel_Forearms);
        jPanel_Forearms.setLayout(jPanel_ForearmsLayout);
        jPanel_ForearmsLayout.setHorizontalGroup(
            jPanel_ForearmsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 333, Short.MAX_VALUE)
        );
        jPanel_ForearmsLayout.setVerticalGroup(
            jPanel_ForearmsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 388, Short.MAX_VALUE)
        );

        jTabbedPane_ArmsHands.addTab("Forearms", jPanel_Forearms);

        org.jdesktop.layout.GroupLayout jPanel_UpperArmsLayout = new org.jdesktop.layout.GroupLayout(jPanel_UpperArms);
        jPanel_UpperArms.setLayout(jPanel_UpperArmsLayout);
        jPanel_UpperArmsLayout.setHorizontalGroup(
            jPanel_UpperArmsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 333, Short.MAX_VALUE)
        );
        jPanel_UpperArmsLayout.setVerticalGroup(
            jPanel_UpperArmsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 388, Short.MAX_VALUE)
        );

        jTabbedPane_ArmsHands.addTab("UpperArms", jPanel_UpperArms);

        org.jdesktop.layout.GroupLayout jPanel_MainArmsHandsLayout = new org.jdesktop.layout.GroupLayout(jPanel_MainArmsHands);
        jPanel_MainArmsHands.setLayout(jPanel_MainArmsHandsLayout);
        jPanel_MainArmsHandsLayout.setHorizontalGroup(
            jPanel_MainArmsHandsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPane_ArmsHands, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );
        jPanel_MainArmsHandsLayout.setVerticalGroup(
            jPanel_MainArmsHandsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPane_ArmsHands, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
        );

        jTabbedPane_Main.addTab("Arms/Hands", jPanel_MainArmsHands);

        jTabbedPane_LegsFeet.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        org.jdesktop.layout.GroupLayout jPanel_FeetLayout = new org.jdesktop.layout.GroupLayout(jPanel_Feet);
        jPanel_Feet.setLayout(jPanel_FeetLayout);
        jPanel_FeetLayout.setHorizontalGroup(
            jPanel_FeetLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 333, Short.MAX_VALUE)
        );
        jPanel_FeetLayout.setVerticalGroup(
            jPanel_FeetLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 388, Short.MAX_VALUE)
        );

        jTabbedPane_LegsFeet.addTab("Feet", jPanel_Feet);

        org.jdesktop.layout.GroupLayout jPanel_CalvesLayout = new org.jdesktop.layout.GroupLayout(jPanel_Calves);
        jPanel_Calves.setLayout(jPanel_CalvesLayout);
        jPanel_CalvesLayout.setHorizontalGroup(
            jPanel_CalvesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 333, Short.MAX_VALUE)
        );
        jPanel_CalvesLayout.setVerticalGroup(
            jPanel_CalvesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 388, Short.MAX_VALUE)
        );

        jTabbedPane_LegsFeet.addTab("Calves", jPanel_Calves);

        org.jdesktop.layout.GroupLayout jPanel_ThighsLayout = new org.jdesktop.layout.GroupLayout(jPanel_Thighs);
        jPanel_Thighs.setLayout(jPanel_ThighsLayout);
        jPanel_ThighsLayout.setHorizontalGroup(
            jPanel_ThighsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 333, Short.MAX_VALUE)
        );
        jPanel_ThighsLayout.setVerticalGroup(
            jPanel_ThighsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 388, Short.MAX_VALUE)
        );

        jTabbedPane_LegsFeet.addTab("Thighs", jPanel_Thighs);

        org.jdesktop.layout.GroupLayout jPanel_LegsFeetLayout = new org.jdesktop.layout.GroupLayout(jPanel_LegsFeet);
        jPanel_LegsFeet.setLayout(jPanel_LegsFeetLayout);
        jPanel_LegsFeetLayout.setHorizontalGroup(
            jPanel_LegsFeetLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 379, Short.MAX_VALUE)
            .add(jPanel_LegsFeetLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jTabbedPane_LegsFeet, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE))
        );
        jPanel_LegsFeetLayout.setVerticalGroup(
            jPanel_LegsFeetLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 409, Short.MAX_VALUE)
            .add(jPanel_LegsFeetLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jTabbedPane_LegsFeet, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE))
        );

        jTabbedPane_Main.addTab("Legs/Feet", jPanel_LegsFeet);

        jTabbedPane_Body.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        org.jdesktop.layout.GroupLayout jPanel_ChestLayout = new org.jdesktop.layout.GroupLayout(jPanel_Chest);
        jPanel_Chest.setLayout(jPanel_ChestLayout);
        jPanel_ChestLayout.setHorizontalGroup(
            jPanel_ChestLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 333, Short.MAX_VALUE)
        );
        jPanel_ChestLayout.setVerticalGroup(
            jPanel_ChestLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 388, Short.MAX_VALUE)
        );

        jTabbedPane_Body.addTab("Chest", jPanel_Chest);

        org.jdesktop.layout.GroupLayout jPanel_AbsLayout = new org.jdesktop.layout.GroupLayout(jPanel_Abs);
        jPanel_Abs.setLayout(jPanel_AbsLayout);
        jPanel_AbsLayout.setHorizontalGroup(
            jPanel_AbsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 333, Short.MAX_VALUE)
        );
        jPanel_AbsLayout.setVerticalGroup(
            jPanel_AbsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 388, Short.MAX_VALUE)
        );

        jTabbedPane_Body.addTab("Abdominals", jPanel_Abs);

        org.jdesktop.layout.GroupLayout jPanel_GlutsLayout = new org.jdesktop.layout.GroupLayout(jPanel_Gluts);
        jPanel_Gluts.setLayout(jPanel_GlutsLayout);
        jPanel_GlutsLayout.setHorizontalGroup(
            jPanel_GlutsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 333, Short.MAX_VALUE)
        );
        jPanel_GlutsLayout.setVerticalGroup(
            jPanel_GlutsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 388, Short.MAX_VALUE)
        );

        jTabbedPane_Body.addTab("Gluts", jPanel_Gluts);

        org.jdesktop.layout.GroupLayout jPanel_UniformBodyLayout = new org.jdesktop.layout.GroupLayout(jPanel_UniformBody);
        jPanel_UniformBody.setLayout(jPanel_UniformBodyLayout);
        jPanel_UniformBodyLayout.setHorizontalGroup(
            jPanel_UniformBodyLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 333, Short.MAX_VALUE)
        );
        jPanel_UniformBodyLayout.setVerticalGroup(
            jPanel_UniformBodyLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 388, Short.MAX_VALUE)
        );

        jTabbedPane_Body.addTab("Uniform", jPanel_UniformBody);

        org.jdesktop.layout.GroupLayout jPanel_BodyLayout = new org.jdesktop.layout.GroupLayout(jPanel_Body);
        jPanel_Body.setLayout(jPanel_BodyLayout);
        jPanel_BodyLayout.setHorizontalGroup(
            jPanel_BodyLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPane_Body, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );
        jPanel_BodyLayout.setVerticalGroup(
            jPanel_BodyLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPane_Body, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
        );

        jTabbedPane_Main.addTab("Body", jPanel_Body);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPane_Main, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPane_Main, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdvOptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel_Abs;
    private javax.swing.JPanel jPanel_Body;
    private javax.swing.JPanel jPanel_Calves;
    private javax.swing.JPanel jPanel_Chest;
    private javax.swing.JPanel jPanel_Eyes;
    private javax.swing.JPanel jPanel_Feet;
    private javax.swing.JPanel jPanel_Forearms;
    private javax.swing.JPanel jPanel_Gluts;
    private javax.swing.JPanel jPanel_Hands;
    private javax.swing.JPanel jPanel_LegsFeet;
    private javax.swing.JPanel jPanel_MainArmsHands;
    private javax.swing.JPanel jPanel_MainHead;
    private javax.swing.JPanel jPanel_Mouth;
    private javax.swing.JPanel jPanel_Nose;
    private javax.swing.JPanel jPanel_Thighs;
    private javax.swing.JPanel jPanel_UniformBody;
    private javax.swing.JPanel jPanel_UniformHead;
    private javax.swing.JPanel jPanel_UpperArms;
    private javax.swing.JTabbedPane jTabbedPane_ArmsHands;
    private javax.swing.JTabbedPane jTabbedPane_Body;
    private javax.swing.JTabbedPane jTabbedPane_Head;
    private javax.swing.JTabbedPane jTabbedPane_LegsFeet;
    private javax.swing.JTabbedPane jTabbedPane_Main;
    // End of variables declaration//GEN-END:variables

}
