/**
 * Project Wonderland
 *
 * Copyright (c) 2004-2008, Sun Microsystems, Inc., All Rights Reserved
 *
 * Redistributions in source code form must reproduce the above
 * copyright and this condition.
 *
 * The contents of this file are subject to the GNU General Public
 * License, Version 2 (the "License"); you may not use this file
 * except in compliance with the License. A copy of the License is
 * available at http://www.opensource.org/licenses/gpl-license.php.
 *
 * Sun designates this particular file as subject to the "Classpath"
 * exception as provided by Sun in the License file that accompanied
 * this code.
 */

/*
 * JPanel_LegsFeetOption.java
 *
 * Created on Dec 17, 2008, 3:08:34 PM
 */

package imi.gui;

/**
 *
 * @author Paul Viet Nguyen Truong (ptruong)
 */
public class JPanel_LegsFeetOption extends javax.swing.JPanel {

    /** Creates new form JPanel_LegsFeetOption */
    public JPanel_LegsFeetOption() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane_LegsFeet = new javax.swing.JTabbedPane();
        jPanel_Upperlegs = new javax.swing.JPanel();
        jPanel_ULLength = new javax.swing.JPanel();
        UpperLeftLeg_Length = new imi.gui.JPanel_VerticalSlider();
        UpperRightLeg_Length = new imi.gui.JPanel_VerticalSlider();
        jCheckBox_SyncULLength = new javax.swing.JCheckBox();
        jPanel_ULThickness = new javax.swing.JPanel();
        UpperLeftLeg_Thickness = new imi.gui.JPanel_HorizontalSlider();
        UpperRightLeg_Thickness = new imi.gui.JPanel_HorizontalSlider();
        jCheckBox_SyncULThickness = new javax.swing.JCheckBox();
        jPanel_Lowerlegs = new javax.swing.JPanel();
        jPanel_LLLength = new javax.swing.JPanel();
        LowerLeftLeg_Length = new imi.gui.JPanel_VerticalSlider();
        LowerRightLeg_Length = new imi.gui.JPanel_VerticalSlider();
        jCheckBox_SyncLLLength = new javax.swing.JCheckBox();
        jPanel_LLThickness = new javax.swing.JPanel();
        LowerLeftLeg_Thickness = new imi.gui.JPanel_HorizontalSlider();
        LowerRightLeg_Thickness = new imi.gui.JPanel_HorizontalSlider();
        jCheckBox_SyncLLThickness = new javax.swing.JCheckBox();
        jPanel_Feet = new javax.swing.JPanel();
        jPanel_FeetLength = new javax.swing.JPanel();
        LeftFoot_Length = new imi.gui.JPanel_VerticalSlider();
        RightFoot_Length = new imi.gui.JPanel_VerticalSlider();
        jCheckBox_SyncFeetLength = new javax.swing.JCheckBox();
        jPanel_FeetThickness = new javax.swing.JPanel();
        LeftFoot_Thickness = new imi.gui.JPanel_HorizontalSlider();
        RightFoot_Thickness = new imi.gui.JPanel_HorizontalSlider();
        jCheckBox_SyncFeetThickness = new javax.swing.JCheckBox();

        setMinimumSize(new java.awt.Dimension(270, 600));
        setPreferredSize(new java.awt.Dimension(270, 600));

        jTabbedPane_LegsFeet.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel_Upperlegs.setLayout(new java.awt.GridBagLayout());

        jPanel_ULLength.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Left & Right Thigh Length", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel_ULLength.setMinimumSize(new java.awt.Dimension(230, 230));
        jPanel_ULLength.setPreferredSize(new java.awt.Dimension(230, 230));
        jPanel_ULLength.setLayout(new java.awt.GridBagLayout());
        jPanel_ULLength.add(UpperLeftLeg_Length, new java.awt.GridBagConstraints());
        jPanel_ULLength.add(UpperRightLeg_Length, new java.awt.GridBagConstraints());

        jCheckBox_SyncULLength.setText("Lock Sliders");
        jCheckBox_SyncULLength.setMinimumSize(new java.awt.Dimension(120, 23));
        jCheckBox_SyncULLength.setPreferredSize(new java.awt.Dimension(120, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        jPanel_ULLength.add(jCheckBox_SyncULLength, gridBagConstraints);

        jPanel_Upperlegs.add(jPanel_ULLength, new java.awt.GridBagConstraints());

        jPanel_ULThickness.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Left & Right Thigh Thickness", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel_ULThickness.setMinimumSize(new java.awt.Dimension(230, 230));
        jPanel_ULThickness.setPreferredSize(new java.awt.Dimension(230, 230));
        jPanel_ULThickness.setLayout(new java.awt.GridBagLayout());

        UpperLeftLeg_Thickness.setMinimumSize(new java.awt.Dimension(109, 57));
        UpperLeftLeg_Thickness.setPreferredSize(new java.awt.Dimension(109, 57));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel_ULThickness.add(UpperLeftLeg_Thickness, gridBagConstraints);

        UpperRightLeg_Thickness.setMinimumSize(new java.awt.Dimension(109, 57));
        UpperRightLeg_Thickness.setParentFrame(null);
        UpperRightLeg_Thickness.setPreferredSize(new java.awt.Dimension(109, 57));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel_ULThickness.add(UpperRightLeg_Thickness, gridBagConstraints);

        jCheckBox_SyncULThickness.setText("Lock Sliders");
        jCheckBox_SyncULThickness.setMinimumSize(new java.awt.Dimension(120, 23));
        jCheckBox_SyncULThickness.setPreferredSize(new java.awt.Dimension(120, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        jPanel_ULThickness.add(jCheckBox_SyncULThickness, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel_Upperlegs.add(jPanel_ULThickness, gridBagConstraints);

        jTabbedPane_LegsFeet.addTab("Thighs", jPanel_Upperlegs);

        jPanel_Lowerlegs.setLayout(new java.awt.GridBagLayout());

        jPanel_LLLength.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Left & Right Calf Length", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel_LLLength.setMinimumSize(new java.awt.Dimension(230, 230));
        jPanel_LLLength.setPreferredSize(new java.awt.Dimension(230, 230));
        jPanel_LLLength.setLayout(new java.awt.GridBagLayout());
        jPanel_LLLength.add(LowerLeftLeg_Length, new java.awt.GridBagConstraints());
        jPanel_LLLength.add(LowerRightLeg_Length, new java.awt.GridBagConstraints());

        jCheckBox_SyncLLLength.setText("Lock Sliders");
        jCheckBox_SyncLLLength.setMinimumSize(new java.awt.Dimension(120, 23));
        jCheckBox_SyncLLLength.setPreferredSize(new java.awt.Dimension(120, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        jPanel_LLLength.add(jCheckBox_SyncLLLength, gridBagConstraints);

        jPanel_Lowerlegs.add(jPanel_LLLength, new java.awt.GridBagConstraints());

        jPanel_LLThickness.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Left & Right Clalf Thickness", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel_LLThickness.setMinimumSize(new java.awt.Dimension(230, 230));
        jPanel_LLThickness.setPreferredSize(new java.awt.Dimension(230, 230));
        jPanel_LLThickness.setLayout(new java.awt.GridBagLayout());

        LowerLeftLeg_Thickness.setMinimumSize(new java.awt.Dimension(109, 57));
        LowerLeftLeg_Thickness.setPreferredSize(new java.awt.Dimension(109, 57));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel_LLThickness.add(LowerLeftLeg_Thickness, gridBagConstraints);

        LowerRightLeg_Thickness.setMinimumSize(new java.awt.Dimension(109, 57));
        LowerRightLeg_Thickness.setParentFrame(null);
        LowerRightLeg_Thickness.setPreferredSize(new java.awt.Dimension(109, 57));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel_LLThickness.add(LowerRightLeg_Thickness, gridBagConstraints);

        jCheckBox_SyncLLThickness.setText("Lock Sliders");
        jCheckBox_SyncLLThickness.setMinimumSize(new java.awt.Dimension(120, 23));
        jCheckBox_SyncLLThickness.setPreferredSize(new java.awt.Dimension(120, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        jPanel_LLThickness.add(jCheckBox_SyncLLThickness, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel_Lowerlegs.add(jPanel_LLThickness, gridBagConstraints);

        jTabbedPane_LegsFeet.addTab("Calves", jPanel_Lowerlegs);

        jPanel_Feet.setLayout(new java.awt.GridBagLayout());

        jPanel_FeetLength.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Left & Right Feet Length", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel_FeetLength.setMinimumSize(new java.awt.Dimension(230, 230));
        jPanel_FeetLength.setPreferredSize(new java.awt.Dimension(230, 230));
        jPanel_FeetLength.setLayout(new java.awt.GridBagLayout());
        jPanel_FeetLength.add(LeftFoot_Length, new java.awt.GridBagConstraints());
        jPanel_FeetLength.add(RightFoot_Length, new java.awt.GridBagConstraints());

        jCheckBox_SyncFeetLength.setText("Lock Sliders");
        jCheckBox_SyncFeetLength.setMinimumSize(new java.awt.Dimension(120, 23));
        jCheckBox_SyncFeetLength.setPreferredSize(new java.awt.Dimension(120, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        jPanel_FeetLength.add(jCheckBox_SyncFeetLength, gridBagConstraints);

        jPanel_Feet.add(jPanel_FeetLength, new java.awt.GridBagConstraints());

        jPanel_FeetThickness.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Left & Right Feet Thickness", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel_FeetThickness.setMinimumSize(new java.awt.Dimension(230, 230));
        jPanel_FeetThickness.setPreferredSize(new java.awt.Dimension(230, 230));
        jPanel_FeetThickness.setLayout(new java.awt.GridBagLayout());

        LeftFoot_Thickness.setMinimumSize(new java.awt.Dimension(109, 57));
        LeftFoot_Thickness.setPreferredSize(new java.awt.Dimension(109, 57));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel_FeetThickness.add(LeftFoot_Thickness, gridBagConstraints);

        RightFoot_Thickness.setMinimumSize(new java.awt.Dimension(109, 57));
        RightFoot_Thickness.setParentFrame(null);
        RightFoot_Thickness.setPreferredSize(new java.awt.Dimension(109, 57));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel_FeetThickness.add(RightFoot_Thickness, gridBagConstraints);

        jCheckBox_SyncFeetThickness.setText("Lock Sliders");
        jCheckBox_SyncFeetThickness.setMinimumSize(new java.awt.Dimension(120, 23));
        jCheckBox_SyncFeetThickness.setPreferredSize(new java.awt.Dimension(120, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        jPanel_FeetThickness.add(jCheckBox_SyncFeetThickness, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel_Feet.add(jPanel_FeetThickness, gridBagConstraints);

        jTabbedPane_LegsFeet.addTab("Feet", jPanel_Feet);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPane_LegsFeet, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 270, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(0, 0, 0)
                .add(jTabbedPane_LegsFeet, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 600, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private imi.gui.JPanel_VerticalSlider LeftFoot_Length;
    private imi.gui.JPanel_HorizontalSlider LeftFoot_Thickness;
    private imi.gui.JPanel_VerticalSlider LowerLeftLeg_Length;
    private imi.gui.JPanel_HorizontalSlider LowerLeftLeg_Thickness;
    private imi.gui.JPanel_VerticalSlider LowerRightLeg_Length;
    private imi.gui.JPanel_HorizontalSlider LowerRightLeg_Thickness;
    private imi.gui.JPanel_VerticalSlider RightFoot_Length;
    private imi.gui.JPanel_HorizontalSlider RightFoot_Thickness;
    private imi.gui.JPanel_VerticalSlider UpperLeftLeg_Length;
    private imi.gui.JPanel_HorizontalSlider UpperLeftLeg_Thickness;
    private imi.gui.JPanel_VerticalSlider UpperRightLeg_Length;
    private imi.gui.JPanel_HorizontalSlider UpperRightLeg_Thickness;
    private javax.swing.JCheckBox jCheckBox_SyncFeetLength;
    private javax.swing.JCheckBox jCheckBox_SyncFeetThickness;
    private javax.swing.JCheckBox jCheckBox_SyncLLLength;
    private javax.swing.JCheckBox jCheckBox_SyncLLThickness;
    private javax.swing.JCheckBox jCheckBox_SyncULLength;
    private javax.swing.JCheckBox jCheckBox_SyncULThickness;
    private javax.swing.JPanel jPanel_Feet;
    private javax.swing.JPanel jPanel_FeetLength;
    private javax.swing.JPanel jPanel_FeetThickness;
    private javax.swing.JPanel jPanel_LLLength;
    private javax.swing.JPanel jPanel_LLThickness;
    private javax.swing.JPanel jPanel_Lowerlegs;
    private javax.swing.JPanel jPanel_ULLength;
    private javax.swing.JPanel jPanel_ULThickness;
    private javax.swing.JPanel jPanel_Upperlegs;
    private javax.swing.JTabbedPane jTabbedPane_LegsFeet;
    // End of variables declaration//GEN-END:variables

}
