/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanel_LegsFeetOption.java
 *
 * Created on Dec 17, 2008, 3:08:34 PM
 */

package imi.gui;

/**
 *
 * @author ptruong
 */
public class JPanel_LegsFeetOption extends javax.swing.JPanel {

    /** Creates new form JPanel_LegsFeetOption */
    public JPanel_LegsFeetOption() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane_LegsFeet = new javax.swing.JTabbedPane();
        jPanel_Upperlegs = new javax.swing.JPanel();
        jPanel_ULLength = new javax.swing.JPanel();
        UpperLeftArm_Length = new imi.gui.JPanel_VerticalSlider();
        UpperRightArm_Length = new imi.gui.JPanel_VerticalSlider();
        jCheckBox_SyncUALength = new javax.swing.JCheckBox();
        jPanel_ULThickness = new javax.swing.JPanel();
        UpperLeftArm_Thickness = new imi.gui.JPanel_HorizontalSlider();
        UpperRightArm_Thickness = new imi.gui.JPanel_HorizontalSlider();
        jCheckBox_SyncUAThickness = new javax.swing.JCheckBox();
        jPanel_Lowerlegs = new javax.swing.JPanel();
        jPanel_Feet = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(270, 600));
        setPreferredSize(new java.awt.Dimension(270, 600));

        jTabbedPane_LegsFeet.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel_Upperlegs.setLayout(new java.awt.GridBagLayout());

        jPanel_ULLength.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Left & Right Upperarm Length", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel_ULLength.setMinimumSize(new java.awt.Dimension(230, 230));
        jPanel_ULLength.setPreferredSize(new java.awt.Dimension(230, 230));
        jPanel_ULLength.setLayout(new java.awt.GridBagLayout());
        jPanel_ULLength.add(UpperLeftArm_Length, new java.awt.GridBagConstraints());
        jPanel_ULLength.add(UpperRightArm_Length, new java.awt.GridBagConstraints());

        jCheckBox_SyncUALength.setText("Lock Sliders");
        jCheckBox_SyncUALength.setMinimumSize(new java.awt.Dimension(120, 23));
        jCheckBox_SyncUALength.setPreferredSize(new java.awt.Dimension(120, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        jPanel_ULLength.add(jCheckBox_SyncUALength, gridBagConstraints);

        jPanel_Upperlegs.add(jPanel_ULLength, new java.awt.GridBagConstraints());

        jPanel_ULThickness.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Left & Right Upperarm Thickness", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel_ULThickness.setMinimumSize(new java.awt.Dimension(230, 230));
        jPanel_ULThickness.setPreferredSize(new java.awt.Dimension(230, 230));
        jPanel_ULThickness.setLayout(new java.awt.GridBagLayout());

        UpperLeftArm_Thickness.setMinimumSize(new java.awt.Dimension(109, 57));
        UpperLeftArm_Thickness.setPreferredSize(new java.awt.Dimension(109, 57));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel_ULThickness.add(UpperLeftArm_Thickness, gridBagConstraints);

        UpperRightArm_Thickness.setMinimumSize(new java.awt.Dimension(109, 57));
        UpperRightArm_Thickness.setParentFrame(null);
        UpperRightArm_Thickness.setPreferredSize(new java.awt.Dimension(109, 57));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel_ULThickness.add(UpperRightArm_Thickness, gridBagConstraints);

        jCheckBox_SyncUAThickness.setText("Lock Sliders");
        jCheckBox_SyncUAThickness.setMinimumSize(new java.awt.Dimension(120, 23));
        jCheckBox_SyncUAThickness.setPreferredSize(new java.awt.Dimension(120, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        jPanel_ULThickness.add(jCheckBox_SyncUAThickness, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel_Upperlegs.add(jPanel_ULThickness, gridBagConstraints);

        jTabbedPane_LegsFeet.addTab("Thighs", jPanel_Upperlegs);

        org.jdesktop.layout.GroupLayout jPanel_LowerlegsLayout = new org.jdesktop.layout.GroupLayout(jPanel_Lowerlegs);
        jPanel_Lowerlegs.setLayout(jPanel_LowerlegsLayout);
        jPanel_LowerlegsLayout.setHorizontalGroup(
            jPanel_LowerlegsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 224, Short.MAX_VALUE)
        );
        jPanel_LowerlegsLayout.setVerticalGroup(
            jPanel_LowerlegsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 579, Short.MAX_VALUE)
        );

        jTabbedPane_LegsFeet.addTab("Calves", jPanel_Lowerlegs);

        org.jdesktop.layout.GroupLayout jPanel_FeetLayout = new org.jdesktop.layout.GroupLayout(jPanel_Feet);
        jPanel_Feet.setLayout(jPanel_FeetLayout);
        jPanel_FeetLayout.setHorizontalGroup(
            jPanel_FeetLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 224, Short.MAX_VALUE)
        );
        jPanel_FeetLayout.setVerticalGroup(
            jPanel_FeetLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 579, Short.MAX_VALUE)
        );

        jTabbedPane_LegsFeet.addTab("Feet", jPanel_Feet);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jTabbedPane_LegsFeet, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 270, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(0, 0, 0)
                .add(jTabbedPane_LegsFeet, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 600, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private imi.gui.JPanel_VerticalSlider UpperLeftArm_Length;
    private imi.gui.JPanel_HorizontalSlider UpperLeftArm_Thickness;
    private imi.gui.JPanel_VerticalSlider UpperRightArm_Length;
    private imi.gui.JPanel_HorizontalSlider UpperRightArm_Thickness;
    private javax.swing.JCheckBox jCheckBox_SyncUALength;
    private javax.swing.JCheckBox jCheckBox_SyncUAThickness;
    private javax.swing.JPanel jPanel_Feet;
    private javax.swing.JPanel jPanel_Lowerlegs;
    private javax.swing.JPanel jPanel_ULLength;
    private javax.swing.JPanel jPanel_ULThickness;
    private javax.swing.JPanel jPanel_Upperlegs;
    private javax.swing.JTabbedPane jTabbedPane_LegsFeet;
    // End of variables declaration//GEN-END:variables

}
