//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.08 at 12:40:05 PM EST 
//


package imi.serialization.xml.bindings;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the imi.serialization.xml.bindings package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Character_QNAME = new QName("http://xml.netbeans.org/schema/CharacterXMLSchema", "Character");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: imi.serialization.xml.bindings
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link xmlMatrix }
     * 
     */
    public xmlMatrix createMatrix() {
        return new xmlMatrix();
    }

    /**
     * Create an instance of {@link xmlFloatRow }
     * 
     */
    public xmlFloatRow createFloatRow() {
        return new xmlFloatRow();
    }

    /**
     * Create an instance of {@link xmlCharacter }
     * 
     */
    public xmlCharacter createCharacter() {
        return new xmlCharacter();
    }

    /**
     * Create an instance of {@link xmlCharacterAttributes }
     * 
     */
    public xmlCharacterAttributes createCharacterAttributes() {
        return new xmlCharacterAttributes();
    }

    /**
     * Create an instance of {@link xmlCharacterAttachmentParameters }
     * 
     */
    public xmlCharacterAttachmentParameters createCharacterAttachmentParameters() {
        return new xmlCharacterAttachmentParameters();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link xmlCharacter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.netbeans.org/schema/CharacterXMLSchema", name = "Character")
    public JAXBElement<xmlCharacter> createCharacter(xmlCharacter value) {
        return new JAXBElement<xmlCharacter>(_Character_QNAME, xmlCharacter.class, null, value);
    }

}
