/**
 * Project Wonderland
 *
 * Copyright (c) 2004-2008, Sun Microsystems, Inc., All Rights Reserved
 *
 * Redistributions in source code form must reproduce the above
 * copyright and this condition.
 *
 * The contents of this file are subject to the GNU General Public
 * License, Version 2 (the "License"); you may not use this file
 * except in compliance with the License. A copy of the License is
 * available at http://www.opensource.org/licenses/gpl-license.php.
 *
 * Sun designates this particular file as subject to the "Classpath" 
 * exception as provided by Sun in the License file that accompanied 
 * this code.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.08 at 12:40:05 PM EST 
//


package imi.serialization.xml.bindings;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for xmlCharacterAttributes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="xmlCharacterAttributes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BaseURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BindPoseFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BodyAnimations" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="FacialAnimations" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DeletionInstructions" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="LoadingInstructions" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AdditionInstructions" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Attachments" type="{http://xml.netbeans.org/schema/CharacterXMLSchema}xmlCharacterAttachmentParameters" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CharacterAttributes", propOrder = {
    "name",
    "gender",
    "baseURL",
    "headAttachment",
    "bodyAnimations",
    "facialAnimations",
    "loadingInstructions",
    "additionInstructions",
    "attachments",
    "eyeballTexture",
    "skinTone"
    
})
public class xmlCharacterAttributes {

    @XmlElement(name = "Name", required = false)
    protected String name;
    @XmlElement(name = "Gender")
    protected int gender;
    @XmlElement(name = "BaseURL", required = false)
    protected String baseURL;
    @XmlElement(name = "HeadAttachment")
    protected String headAttachment;
    @XmlElement(name = "BodyAnimations")
    protected List<String> bodyAnimations;
    @XmlElement(name = "FacialAnimations")
    protected List<String> facialAnimations;
    @XmlElement(name = "LoadingInstructions")
    protected List<String> loadingInstructions;
    @XmlElement(name = "AdditionInstructions")
    protected List<xmlSkinnedMeshParams> additionInstructions;
    @XmlElement(name = "Attachments")
    protected List<xmlCharacterAttachmentParameters> attachments;
    @XmlElement(name = "EyeballTexture")
    protected String eyeballTexture;
    @XmlElement(name = "SkinTone")
    protected xmlFloatRow skinTone;


    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    public String getEyeballTexture() {
        return eyeballTexture;
    }

    public void setEyeballTexture(String eyeballTexture) {
        this.eyeballTexture = eyeballTexture;
    }

    public xmlFloatRow getSkinTone() {
        return skinTone;
    }

    public void setSkinTone(xmlFloatRow skinTone) {
        this.skinTone = skinTone;
    }


    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the baseURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseURL() {
        return baseURL;
    }

    /**
     * Sets the value of the baseURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseURL(String value) {
        this.baseURL = value;
    }

    public String getHeadAttachment() {
        return headAttachment;
    }

    public void setHeadAttachment(String value) {
        headAttachment = value;
    }


    /**
     * Gets the value of the bodyAnimations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bodyAnimations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBodyAnimations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getBodyAnimations() {
        if (bodyAnimations == null) {
            bodyAnimations = new ArrayList<String>();
        }
        return this.bodyAnimations;
    }
    
    public int getBodyAnimationCount()
    {
        if (bodyAnimations == null)
            return 0;
        else return bodyAnimations.size();
    }

    public void setBodyAnimations(List<String> animationList) {
        bodyAnimations = animationList;
    }

    public void addBodyAnimation(String animationString)
    {
        if (bodyAnimations == null)
            bodyAnimations = new ArrayList<String>();
        bodyAnimations.add(animationString);
    }

    public void clearBodyAnimationList()
    {
        if (bodyAnimations != null)
        {
            bodyAnimations.clear();
            bodyAnimations = null;
        }
    }

    /**
     * Gets the value of the facialAnimations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the facialAnimations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFacialAnimations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getFacialAnimations() {
        if (facialAnimations == null) {
            facialAnimations = new ArrayList<String>();
        }
        return this.facialAnimations;
    }

    public int getFacialAnimationCount()
    {
        if (facialAnimations == null)
            return 0;
        else return facialAnimations.size();
    }

    public void setFacialAnimations(List<String> animationList) {
        facialAnimations = animationList;
    }

    public void addFacialAnimation(String animationString)
    {
        if (facialAnimations == null)
            facialAnimations = new ArrayList<String>();
        facialAnimations.add(animationString);
    }

    public void clearFacialAnimationList()
    {
        if (facialAnimations != null)
        {
            facialAnimations.clear();
            facialAnimations = null;
        }
    }

    /**
     * Gets the value of the loadingInstructions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the loadingInstructions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLoadingInstructions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLoadingInstructions() {
        if (loadingInstructions == null) {
            loadingInstructions = new ArrayList<String>();
        }
        return this.loadingInstructions;
    }

    public int getLoadingInstructionCount()
    {
        if (loadingInstructions == null)
            return 0;
        else return loadingInstructions.size();
    }

    public void setLoadingInstructions(List<String> instructionList) {
        loadingInstructions = instructionList;
    }

    public void addLoadingInstruction(String instructionString)
    {
        if (loadingInstructions == null)
            loadingInstructions = new ArrayList<String>();
        loadingInstructions.add(instructionString);
    }

    public void clearLoadingInstructionList()
    {
        if (loadingInstructions != null)
        {
            loadingInstructions.clear();
            loadingInstructions = null;
        }
    }
    /**
     * Gets the value of the additionInstructions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionInstructions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionInstructions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<xmlSkinnedMeshParams> getAdditionInstructions() {
        if (additionInstructions == null) {
            additionInstructions = new ArrayList<xmlSkinnedMeshParams>();
        }
        return this.additionInstructions;
    }

    public int getAdditionInstructionCount()
    {
        if (additionInstructions == null)
            return 0;
        else return additionInstructions.size();
    }

    public void setAdditionInstructions(List<xmlSkinnedMeshParams> instructionList) {
        additionInstructions = instructionList;
    }

    public void addAdditionInstruction(xmlSkinnedMeshParams params)
    {
        if (additionInstructions == null)
            additionInstructions = new ArrayList<xmlSkinnedMeshParams>();
        additionInstructions.add(params);
    }

    public void clearAdditionInstructionList()
    {
        if (additionInstructions != null)
        {
            additionInstructions.clear();
            additionInstructions = null;
        }
    }

    /**
     * Gets the value of the attachments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attachments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttachments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link xmlCharacterAttachmentParameters }
     * 
     * 
     */
    public List<xmlCharacterAttachmentParameters> getAttachments() {
        if (attachments == null) {
            attachments = new ArrayList<xmlCharacterAttachmentParameters>();
        }
        return this.attachments;
    }

    public int getAttachmentCount()
    {
        if (attachments == null)
            return 0;
        else return attachments.size();
    }

    public void setAttachments(List<xmlCharacterAttachmentParameters> instructionList) {
        attachments = instructionList;
    }

    public void addAttachment(xmlCharacterAttachmentParameters attachment)
    {
        if (attachments == null)
            attachments = new ArrayList<xmlCharacterAttachmentParameters>();
        attachments.add(attachment);
    }

    public void clearAttachmentList()
    {
        if (attachments != null)
        {
            attachments.clear();
            attachments = null;
        }
    }

    public int getGender()
    {
        return gender;
    }

    public void setGender(int gender)
    {
        this.gender = gender;
    }
}
