//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.08 at 12:40:05 PM EST 
//


package imi.serialization.xml.bindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for xmlCharacterAttachmentParameters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="xmlCharacterAttachmentParameters">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MeshName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="JointToAttachOn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LocalSpaceTransform" type="{http://xml.netbeans.org/schema/CharacterXMLSchema}xmlMatrix"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CharacterAttachmentParameters", propOrder = {
    "meshName",
    "jointToAttachOn",
    "localSpaceTransform"
})
public class xmlCharacterAttachmentParameters {

    @XmlElement(name = "MeshName", required = true)
    protected String meshName;
    @XmlElement(name = "JointToAttachOn", required = true)
    protected String jointToAttachOn;
    @XmlElement(name = "LocalSpaceTransform", required = true)
    protected xmlMatrix localSpaceTransform;

    /**
     * Gets the value of the meshName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeshName() {
        return meshName;
    }

    /**
     * Sets the value of the meshName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeshName(String value) {
        this.meshName = value;
    }

    /**
     * Gets the value of the jointToAttachOn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJointToAttachOn() {
        return jointToAttachOn;
    }

    /**
     * Sets the value of the jointToAttachOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJointToAttachOn(String value) {
        this.jointToAttachOn = value;
    }

    /**
     * Gets the value of the localSpaceTransform property.
     * 
     * @return
     *     possible object is
     *     {@link xmlMatrix }
     *     
     */
    public xmlMatrix getLocalSpaceTransform() {
        return localSpaceTransform;
    }

    /**
     * Sets the value of the localSpaceTransform property.
     * 
     * @param value
     *     allowed object is
     *     {@link xmlMatrix }
     *     
     */
    public void setLocalSpaceTransform(xmlMatrix value) {
        this.localSpaceTransform = value;
    }

}
