//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.17 at 12:30:48 PM EST 
//


package imi.serialization.xml.bindings;

import com.jme.scene.state.CullState.Face;
import com.jme.scene.state.MaterialState.ColorMaterial;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for xmlMaterial complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="xmlMaterial">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Textures" type="{http://xml.netbeans.org/schema/CharacterXMLSchema}xmlTextureAttributes" maxOccurs="8"/>
 *         &lt;element name="DiffuseColor" type="{http://xml.netbeans.org/schema/CharacterXMLSchema}xmlColorRGBA"/>
 *         &lt;element name="AmbientColor" type="{http://xml.netbeans.org/schema/CharacterXMLSchema}xmlColorRGBA"/>
 *         &lt;element name="EmissiveColor" type="{http://xml.netbeans.org/schema/CharacterXMLSchema}xmlColorRGBA"/>
 *         &lt;element name="SpecularColor" type="{http://xml.netbeans.org/schema/CharacterXMLSchema}xmlColorRGBA"/>
 *         &lt;element name="TransparencyColor" type="{http://xml.netbeans.org/schema/CharacterXMLSchema}xmlColorRGBA"/>
 *         &lt;element name="Shaders" type="{http://xml.netbeans.org/schema/CharacterXMLSchema}xmlShader" maxOccurs="unbounded"/>
 *         &lt;element name="Shininess" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="ColorMaterial" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CullFace" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="TargetMeshName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Material", propOrder = {
    "textures",
    "diffuseColor",
    "ambientColor",
    "emissiveColor",
    "specularColor",
    "transparencyColor",
    "shaders",
    "shininess",
    "colorMaterial",
    "cullFace",
    "name",
    "alphaState"
})
public class xmlMaterial {

    @XmlElement(name = "Textures", required = true)
    protected List<xmlTextureAttributes> textures;
    @XmlElement(name = "DiffuseColor")
    protected xmlColorRGBA diffuseColor;
    @XmlElement(name = "AmbientColor")
    protected xmlColorRGBA ambientColor;
    @XmlElement(name = "EmissiveColor")
    protected xmlColorRGBA emissiveColor;
    @XmlElement(name = "SpecularColor")
    protected xmlColorRGBA specularColor;
    @XmlElement(name = "TransparencyColor")
    protected xmlColorRGBA transparencyColor;
    @XmlElement(name = "Shaders", required = true)
    protected List<xmlShader> shaders;
    @XmlElement(name = "Shininess")
    protected int shininess;
    @XmlElement(name = "ColorMaterial", required = true)
    protected String colorMaterial;
    @XmlElement(name = "CullFace", required = true)
    protected String cullFace;
    @XmlAttribute(name = "Name", required = true)
    protected String name;
    @XmlAttribute(name = "TargetMeshName")
    protected String targetMeshName;
    @XmlAttribute(name = "AlphaState")
    protected Integer alphaState;

    /**
     * Gets the value of the textures property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the textures property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTextures().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link xmlTextureAttributes }
     * 
     * 
     */
    public List<xmlTextureAttributes> getTextures() {
        if (textures == null) {
            textures = new ArrayList<xmlTextureAttributes>();
        }
        return this.textures;
    }

    public void addTexture(xmlTextureAttributes textureAttributes)
    {
        getTextures().add(textureAttributes);
    }

    public Integer getAlphaState()
    {
        return alphaState;
    }

    public void setAlphaState(Integer value)
    {
        alphaState = value;
    }
    /**
     * Gets the value of the diffuseColor property.
     * 
     * @return
     *     possible object is
     *     {@link xmlColorRGBA }
     *     
     */
    public xmlColorRGBA getDiffuseColor() {
        return diffuseColor;
    }

    /**
     * Sets the value of the diffuseColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link xmlColorRGBA }
     *     
     */
    public void setDiffuseColor(xmlColorRGBA value) {
        this.diffuseColor = value;
    }

    /**
     * Gets the value of the ambientColor property.
     * 
     * @return
     *     possible object is
     *     {@link xmlColorRGBA }
     *     
     */
    public xmlColorRGBA getAmbientColor() {
        return ambientColor;
    }

    /**
     * Sets the value of the ambientColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link xmlColorRGBA }
     *     
     */
    public void setAmbientColor(xmlColorRGBA value) {
        this.ambientColor = value;
    }

    /**
     * Gets the value of the emissiveColor property.
     * 
     * @return
     *     possible object is
     *     {@link xmlColorRGBA }
     *     
     */
    public xmlColorRGBA getEmissiveColor() {
        return emissiveColor;
    }

    /**
     * Sets the value of the emissiveColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link xmlColorRGBA }
     *     
     */
    public void setEmissiveColor(xmlColorRGBA value) {
        this.emissiveColor = value;
    }

    /**
     * Gets the value of the specularColor property.
     * 
     * @return
     *     possible object is
     *     {@link xmlColorRGBA }
     *     
     */
    public xmlColorRGBA getSpecularColor() {
        return specularColor;
    }

    /**
     * Sets the value of the specularColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link xmlColorRGBA }
     *     
     */
    public void setSpecularColor(xmlColorRGBA value) {
        this.specularColor = value;
    }

    /**
     * Gets the value of the transparencyColor property.
     * 
     * @return
     *     possible object is
     *     {@link xmlColorRGBA }
     *     
     */
    public xmlColorRGBA getTransparencyColor() {
        return transparencyColor;
    }

    /**
     * Sets the value of the transparencyColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link xmlColorRGBA }
     *     
     */
    public void setTransparencyColor(xmlColorRGBA value) {
        this.transparencyColor = value;
    }

    /**
     * Gets the value of the shaders property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the shaders property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getShaders().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link xmlShader }
     * 
     * 
     */
    public List<xmlShader> getShaders() {
        if (shaders == null) {
            shaders = new ArrayList<xmlShader>();
        }
        return this.shaders;
    }

    public void addShader(xmlShader shader)
    {
        getShaders().add(shader);
    }

    /**
     * Gets the value of the shininess property.
     * 
     */
    public int getShininess() {
        return shininess;
    }

    /**
     * Sets the value of the shininess property.
     * 
     */
    public void setShininess(int value) {
        this.shininess = value;
    }

    /**
     * Gets the value of the colorMaterial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColorMaterial() {
        return colorMaterial;
    }

    public ColorMaterial getColorMaterialAsColorMaterial()
    {
        ColorMaterial result = ColorMaterial.valueOf(this.colorMaterial);
        return result;
    }
    /**
     * Sets the value of the colorMaterial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColorMaterial(String value) {
        this.colorMaterial = value;
    }

    public void setColorMaterial(ColorMaterial mat)
    {
        this.colorMaterial = mat.toString();
    }

    /**
     * Gets the value of the cullFace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCullFace() {
        return cullFace;
    }

    /**
     * Sets the value of the cullFace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCullFace(String value) {
        this.cullFace = value;
    }

    public void setCullFace(Face cullFace) {
        this.cullFace = cullFace.toString();
    }

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the targetMeshName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetMeshName() {
        return targetMeshName;
    }

    /**
     * Sets the value of the targetMeshName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetMeshName(String value) {
        this.targetMeshName = value;
    }

}
