//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.17 at 12:30:48 PM EST 
//


package imi.serialization.xml.bindings;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for xmlShader complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="xmlShader">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Program" type="{http://xml.netbeans.org/schema/CharacterXMLSchema}xmlShaderProgram"/>
 *         &lt;element name="Properties" type="{http://xml.netbeans.org/schema/CharacterXMLSchema}xmlShaderProperty" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Shader", propOrder = {
    "program",
    "properties"
})
public class xmlShader {

    @XmlElement(name = "Program", required = true)
    protected xmlShaderProgram program;
    @XmlElement(name = "Properties", required = true)
    protected List<xmlShaderProperty> properties;

    /**
     * Gets the value of the program property.
     * 
     * @return
     *     possible object is
     *     {@link xmlShaderProgram }
     *     
     */
    public xmlShaderProgram getProgram() {
        return program;
    }

    /**
     * Sets the value of the program property.
     * 
     * @param value
     *     allowed object is
     *     {@link xmlShaderProgram }
     *     
     */
    public void setProgram(xmlShaderProgram value) {
        this.program = value;
    }

    /**
     * Gets the value of the properties property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the properties property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperties().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link xmlShaderProperty }
     * 
     * 
     */
    public List<xmlShaderProperty> getProperties() {
        if (properties == null) {
            properties = new ArrayList<xmlShaderProperty>();
        }
        return this.properties;
    }

    public void addShaderProperty(xmlShaderProperty newProperty)
    {
        getProperties().add(newProperty);
    }

}
