//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.17 at 12:30:48 PM EST 
//


package imi.serialization.xml.bindings;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for xmlShaderProgram complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="xmlShaderProgram">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="DefaultProgramName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ListOfEffects" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ShaderProgram", propOrder = {
    "defaultProgramName",
    "listOfEffects"
})
public class xmlShaderProgram {

    @XmlElement(name = "DefaultProgramName")
    protected String defaultProgramName;
    @XmlElement(name = "ListOfEffects")
    protected List<String> listOfEffects;

    /**
     * Gets the value of the defaultProgramName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultProgramName() {
        return defaultProgramName;
    }

    /**
     * Sets the value of the defaultProgramName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultProgramName(String value) {
        this.defaultProgramName = value;
    }

    /**
     * Gets the value of the listOfEffects property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the listOfEffects property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getListOfEffects().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getListOfEffects() {
        if (listOfEffects == null) {
            listOfEffects = new ArrayList<String>();
        }
        return this.listOfEffects;
    }

    public void addEffect(String effectName)
    {
        getListOfEffects().add(effectName);
    }

}
